x=10
y=20
print("Addition:", x + y)
print("Subtraction:", y - x)
print("Multiplication:", x * y)
print("Division:", y / x)
print("Floor Division:", y // x)
print("Modulus:", y % x)
print("Exponentiation:", x ** 2)
print("Comparison (x < y):", x < y)
print("Comparison (x > y):", x > y)
print("Equality (x == y):", x == y)
print("Inequality (x != y):", x != y)
print(x<15 and y>15)
print(x<15 or y<15)
print(not(x<y))
print("Bitwise AND:", x & y)          
print("Bitwise OR:", x | y)          
print("Bitwise XOR:", x ^ y)
print("Bitwise NOT of x:", ~x)
print("Left Shift x by 2:", x << 2)
print("Right Shift y by 2:", y >> 2)
print("Identity (x is y):", x is y)
print("Identity (x is not y):", x is not y)
print("Membership ('10' in '1020'):", '10' in '1020')